language: python

python:
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - git clone "https://github.com/mozilla/send.git" && cd send && git checkout `git describe --tags --abbrev=0 --match v[0-9+]\.[0-9+]\.[0-9+]` 
  - nvm install node && npm install
  - npm start & cd ../ && sleep 15
  - pip install .

script:
  - pytest
  - send-cli -h
